#!/usr/bin/env ruby

# This is the starting script for the Graphical Editor.
# The Graphical Editor is an implementation of the graphical editor as defined
# in the README file
#
# To run script:
#
# - ./main.rb


# Error classes that are used by the graphical editor to register exceptions
# and manage program flow
class GraphicEditorError < StandardError
end
class ExitGraphicEditorError < StandardError
end

# require all the models
Dir[File.dirname(__FILE__) + '/models/*.rb'].each {|file| require File.expand_path(file) }

int = Dispatcher.new
quit = false

# collect and process input until we need to quit
until quit
  print "> "
  x = readline

  begin
    int.execute(x)
  # catch and handle exceptions generated by the graphical editor
  rescue GraphicEditorError  => e
    puts e.message
  # catch the exit exception signal
  rescue ExitGraphicEditorError
    quit = true
  end
end